#!/usr/bin/env python2.7
# coding: utf-8

import argparse
from operator import itemgetter
import json
from string import Template
import sys

html = Template(u"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="refresh" content="10">
    $head_title

    <style type="text/css">
    html {
        background-color: #000000;
        font-family: Oswald;
        height: 100%;
    }
    body {
        height: 100%;
        overflow: hidden;
        margin: 0;
    }
    body.ok {
        background: #00ff06;
        background: -moz-linear-gradient(top, #00ff06 0%, #007f00 100%);
        background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #00ff06), color-stop(100%, #007f00));
        background: -webkit-linear-gradient(top, #00ff06 0%, #007f00 100%);
        background: linear-gradient(to bottom, #00ff06 0%, #007f00 100%);
    }
    body.warning {
        background: #b28800;
        background: -moz-linear-gradient(top, #b28800 0%, #4c3a00 100%);
        background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #b28800), color-stop(100%, #4c3a00));
        background: -webkit-linear-gradient(top, #b28800 0%, #4c3a00 100%);
        background: linear-gradient(to bottom, #b28800 0%, #4c3a00 100%);
    }
    body.warning div.allokay { display: none; }
    body.unknown {
        background: #7402cc;
        background: -moz-linear-gradient(top, #7402cc 0%, #3a0166 100%);
        background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #7402cc), color-stop(100%, #3a0166));
        background: -webkit-linear-gradient(top, #7402cc 0%, #3a0166 100%);
        background: linear-gradient(to bottom, #7402cc 0%, #3a0166 100%);
    }
    body.unknown div.allokay { display: none; }
    body.critical, body.failed {
        background: #7f0000;
        background: -moz-linear-gradient(top, #7f0000 0%, #300000 100%);
        background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #7f0000), color-stop(100%, #300000));
        background: -webkit-linear-gradient(top, #7f0000 0%, #300000 100%);
        background: linear-gradient(to bottom, #7f0000 0%, #300000 100%);
    }
    body.critical div.allokay, body.failed div.allokay { display: none; }
    @-moz-keyframes fade {
        0% { opacity: 0.03 }
        50% { opacity: 0.4 }
        100% { opacity: 0.03 }
    }
    @-webkit-keyframes fade {
        0% { opacity: 0.03 }
        50% { opacity: 0.4 }
        100% { opacity: 0.03 }
    }
    @keyframes fade {
        0% { opacity: 0.03 }
        50% { opacity: 0.4 }
        100% { opacity: 0.03 }
    }
    div.failed-overlay {
        background-color: #ff0000;
        display: none;
        height: 100%;
        opacity: 0.03;
        position: fixed;
        width: 100%;
        -webkit-animation: fade 5s infinite;
        -moz-animation: fade 5s infinite;
        animation: fade 5s infinite;
    }
    body.failed div.failed-overlay { display: flex; }
    div.title {
        background-color: rgba(0,0,0, 0.4);
        color: #eeeeee;
        font-size: 48px;
        padding-top: 7px;
        padding-bottom: 6px;
        text-align: center;
        width: 100%;
    }
    table {
        width: 100%;
        border-spacing: 0;
    }
    div.allokay {
        font-size: 700px;
        height: 700px;
        margin-top: -580px;
        opacity: 0.03;
        position: fixed;
        text-align: center;
        top: 50%;
        width: 100%;

        -webkit-animation: fade 4s;
        -moz-animation: fade 4s;
        animation: fade 4s;
    }
    tr { width: 100%; text-shadow: 1px 1px 0px rgba(255, 255, 255, 0.4); }
    tr.soft td {
          background: rgba(255, 255, 255, 0.2);
          text-shadow: 1px 1px 0px rgba(255, 255, 255, 0.2);
    }
    tr.warning {
        background: #ffd519;
        background: -moz-linear-gradient(top,  #ffd519 0%, #e5bf16 100%);
        background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#ffd519), color-stop(100%,#e5bf16));
        background: -webkit-linear-gradient(top,  #ffd519 0%,#e5bf16 100%);
        background: linear-gradient(to bottom,  #ffd519 0%,#e5bf16 100%);
    }
    tr.warning.detail { background: #e5bf16; }
    tr.warning.soft { color: #A68700; }
    tr.warning.soft.detail { color: #A68700; }
    tr.critical, tr.failed {
        background: #ff0000;
        background: -moz-linear-gradient(top,  #ff0000 0%, #d30000 100%);
        background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#ff0000), color-stop(100%,#d30000));
        background: -webkit-linear-gradient(top,  #ff0000 0%,#d30000 100%);
        background: linear-gradient(to bottom,  #ff0000 0%,#d30000 100%);
    }
    tr.critical.detail, tr.failed.detail { background: #d30000; }
    tr.critical.soft { color: #8C0000; }
    tr.critical.soft.detail { color: #8C0000; }
    tr.unknown {
        background: #ff32ff;
        background: -moz-linear-gradient(top,  #ff32ff 0%, #cc3dcc 100%);
        background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#ff32ff), color-stop(100%,#cc3dcc));
        background: -webkit-linear-gradient(top,  #ff32ff 0%,#cc3dcc 100%);
        background: linear-gradient(to bottom,  #ff32ff 0%,#cc3dcc 100%);
    }
    tr.unknown.detail { background: #cc3dcc; }
    tr.unknown.soft { color: #A800A8; }
    tr.unknown.soft.detail { color: #A800A8; }
    tr.ok {
        background: #00ff06;
        background: -moz-linear-gradient(top,  #00ff06 0%, #00cc00 100%);
        background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#00ff06), color-stop(100%,#00cc00));
        background: -webkit-linear-gradient(top,  #00ff06 0%,#00cc00 100%);
        background: linear-gradient(to bottom,  #00ff06 0%,#00cc00 100%);
    }
    tr.ok.detail { background: #00cc00; }
    tr.ok.soft { color: #00A803; }
    tr.ok.soft.detail { color: #00A803; }
    td {
        font-size: 60px;
        padding-top: 10px;
        padding-bottom: 9px;
        padding-left: 15px;
        padding-right: 10px;
    }
    tr.detail td {
        font-size: 22px;
        padding-top: 0;
        white-space: nowrap;
    }
    </style>
</head>
<body class="ok $bodyclasses">
    <div class="failed-overlay"></div>
    $div_title
    <div class="allokay">☺</div>
    <table>
$tablerows
    </table>
</body>
</html>
""")

parser = argparse.ArgumentParser()
parser.add_argument('-e', '--exclude_hosts', nargs='+', default=[])
parser.add_argument('-E', '--exclude_services', nargs='+', default=[])
parser.add_argument('-o', '--only_services', nargs='+', default=[])
parser.add_argument('-t', '--title')
parser.add_argument('-T', '--template')
parser.add_argument('-i', '--input', default='/tmp/raw-textios-data')
parser.add_argument('location', nargs='+')
args = parser.parse_args()

if args.title:
    div_title = '<div class="title">{}</div>'.format(args.title)
    head_title = '<title>{}</title>'.format(args.title)
else:
    div_title = head_title = ''

if args.template:
    try:
        with open(args.template, 'r') as fp:
            html = Template(fp.read().decode('UTF-8'))
    except IOError:
        sys.stderr.write('Cannot read HTML template\n')
        sys.exit(1)

buffered = []
statusmapping = {
    'failed': 0,
    'critical': 1,
    'unknown': 2,
    'warning': 3,
    'ok': 4,
}
hoststatusmapping = {
    'down': 'critical',
    'unreachable': 'unknown',
    'up': 'ok',
}
statusmappinginv = { v: k for k, v in statusmapping.items() }

for l in args.location:
    if l == 'NONE':
        continue

    failed = False
    try:
        with open('{}/{}/hosts.json'.format(args.input, l), 'r') as fp:
            info_hosts = json.load(fp)

        with open('{}/{}/services.json'.format(args.input, l), 'r') as fp:
            info_services = json.load(fp)
    except:
        failed = True
        info_hosts = {'status': {'host_status': []}}
        info_services = {'status': {'service_status': []}}

    if not 'status' in info_hosts.keys() or not 'status' in info_services.keys():
        failed = True

    if failed:
        buffered.append((l, 'FAILED', statusmapping['failed'], False,
                         'Unable to read textios data.', False))
        continue

    hosts_downtime = set(args.exclude_hosts)
    for host in info_hosts['status']['host_status']:
        if host['in_scheduled_downtime']:
            hosts_downtime.add(host['host_name'])

        if host['host_name'] in hosts_downtime:
            continue

        if args.only_services:
            # This is a bit misleading. The "if" does not check if we're
            # to show *only services* -- it checks if we're to show only
            # *CERTAIN* services. A host check is never a service check.
            # Thus, with "-o", we must never show any host problems.
            continue

        if host['status'].lower() in ['up', 'pending']:
            continue

        buffered.append((host['host_display_name'], 'HOST',
                         statusmapping[hoststatusmapping[host['status'].lower()]],
                         host['state_type'] == 'SOFT', 'Host problem',
                         host['has_been_acknowledged']))

    for service in info_services['status']['service_status']:
        if service['status'].lower() in ['ok', 'pending']:
            continue

        if service['host_name'] in hosts_downtime or \
            service['in_scheduled_downtime']:
            continue

        if args.only_services and service['service_display_name'] not in \
            args.only_services:
            continue

        if args.exclude_services and service['service_display_name'] \
            in args.exclude_services:
            continue

        buffered.append((service['host_display_name'],
                         service['service_display_name'],
                         statusmapping[service['status'].lower()],
                         service['state_type'] == 'SOFT',
                         service['status_information'],
                         service['has_been_acknowledged']))

buffered = sorted(buffered, key=itemgetter(3, 2, 0, 1))

bodyclasses = set()
tablerows = ''

for host, service, numericalstatus, soft, detail, acked in buffered:
    status = statusmappinginv[numericalstatus]
    hardness = u'soft' if soft else u'hard'
    acked = u'ACKNOWLEDGED' if acked else u''
    bodyclasses.add(status)

    tablerows += (
        u'<tr class="{status} {hardness}">'
        u'<td class="host">{host}</td>'
        u'<td class="service">{service}</td>'
        u'</tr>\n'
        u'<tr class="detail {status} {hardness}">'
        u'<td>{acked}</td><td>{detail}</td></tr>'
    ).format(
        status=status,
        hardness=hardness,
        host=host.replace(u'-', u'&#8209;'),
        service=service,
        detail=detail,
        acked=acked,
    )

complete = html.substitute(
    bodyclasses=u' '.join(bodyclasses),
    div_title=div_title,
    head_title=head_title,
    tablerows=tablerows,
)
print complete.encode('UTF-8')
