#!/bin/bash

if [[ ! -f ~/.textiosrc ]]
then
	echo 'Cannot read ~/.textiosrc' >&2
	exit 1
fi

. ~/.textiosrc

filters='CRITICAL UNKNOWN'
while getopts aw name
do
	case $name in
		a)
			filters=
			;;
		w)
			filters='WARNING CRITICAL UNKNOWN'
			;;
	esac
done

rm -f /tmp/textios-*

for (( i = 0; i < "${#monitors[@]}"; i += 4 ))
do
	printf -v suff '%02d-%s' $i ${monitors[$i]}
	echo Fetching $suff...
	case ${monitors[$((i + 1))]} in
		icinga)
			curl -nsLk "${monitors[$((i + 2))]}" |
				sed 1d | textios-csv_to_editable $filters \
					>/tmp/textios-$suff
			;;
		nagios)
			curl -nsLk "${monitors[$((i + 2))]}" | textios-nagios_to_csv |
				sed 1d | textios-csv_to_editable $filters \
					>/tmp/textios-$suff
			;;
	esac
done

vim -o /tmp/textios-*

for (( i = 0; i < "${#monitors[@]}"; i += 4 ))
do
	printf -v suff '%02d-%s' $i ${monitors[$i]}
	echo Processing $suff...
	textios-process_editable "${monitors[$((i + 3))]}" \
		</tmp/textios-$suff
done
