#!/usr/bin/env python2
# coding: utf-8

import sys
import re
import datetime
import subprocess
import getpass

url = sys.argv[1]

for line in sys.stdin.readlines():
    # An nbsp auftrennen:
    tokens = [i.strip() for i in line.split(' ')]

    cmd = tokens[0]
    host = tokens[1]
    service = tokens[2]

    # Erlaubt:
    #  ack
    #  ack irgendein kommentar
    m = re.search(r'^ack( (.*))?', cmd, re.I)
    if m:
        comment = m.group(2) or 'Acknowledged'
        print 'ack {} on {}'.format(service, host)
        curlcmd = ['curl', '-nsLk', '--fail', url,
                   '--data', 'cmd_typ=34',
                   '--data', 'cmd_mod=2',
                   '--data', 'com_author={}'.format(getpass.getuser()),
                   '--data', 'host={}'.format(host),
                   '--data', 'service={}'.format(service),
                   '--data', 'com_data={}'.format(comment),
                   '--data', 'sticky_ack=1',
                   '--data', 'send_notification=1',
                   '--data', 'persistent=1']
        with open('/dev/null', 'w') as fp:
            if subprocess.call(curlcmd, stdout=fp) != 0:
                sys.stderr.write('ACK {} {} failed'.format(host, service))

    # Erlaubt:
    #
    #  down
    #  down datum kommentar
    #  down datum uhrzeit kommentar
    #  down uhrzeit kommentar
    #
    # - "datum" defaults to heute.
    # - "uhrzeit" defaults to 12:00.
    # - Uhrzeiten immer mit Stunden und Minuten, beide zweistellig.
    # - "hdown" statt "down" für eine Host-Downtime.
    m = re.search(r'^(h?)down( (\+\d+|(\d{4}-\d{2}-\d{2})? ?(\d{2}:\d{2})?) ?(.*))?',
                  cmd, re.I)
    if m:
        two_hours_later = datetime.datetime.now() + datetime.timedelta(hours=2)

        host_downtime = False
        if m.group(1) == 'h':
            host_downtime = True

        if not m.group(3) or not m.group(3).startswith('+'):
            if not m.group(4) and not m.group(5):
                date = two_hours_later.strftime('%Y-%m-%d')
            elif not m.group(4) and m.group(5):
                date = datetime.datetime.now().strftime('%Y-%m-%d')
            else:
                date = m.group(4)

            if not m.group(5) and not m.group(4):
                time = two_hours_later.strftime('%H:%M') + ':00'
            elif not m.group(5) and m.group(4):
                time = '12:00:00'
            else:
                time = m.group(5) + ':00'
        else:
            added = datetime.datetime.now() + \
                    datetime.timedelta(hours=int(m.group(3)))
            date = added.strftime('%Y-%m-%d')
            time = added.strftime('%H:%M:00')

        comment = m.group(6) or 'Scheduled Downtime'
        starttime = datetime.datetime.now().strftime('%F %T')

        if host_downtime:
            print 'host downtime for {}'.format(host)
            curlcmd = [
                       'curl', '-nsLk', '--fail', url,
                       '--data', 'cmd_typ=55',
                       '--data', 'cmd_mod=2',
                       '--data', 'com_author={}'.format(getpass.getuser()),
                       '--data', 'host={}'.format(host),
                       '--data', 'com_data={}'.format(comment),
                       '--data', 'start_time={}'.format(starttime),
                       '--data', 'end_time={} {}'.format(date, time),
                       '--data', 'fixed=1',
                      ]
        else:
            print 'service downtime for {} on {}'.format(service, host)
            curlcmd = [
                       'curl', '-nsLk', '--fail', url,
                       '--data', 'cmd_typ=56',
                       '--data', 'cmd_mod=2',
                       '--data', 'com_author={}'.format(getpass.getuser()),
                       '--data', 'host={}'.format(host),
                       '--data', 'service={}'.format(service),
                       '--data', 'com_data={}'.format(comment),
                       '--data', 'start_time={}'.format(starttime),
                       '--data', 'end_time={} {}'.format(date, time),
                       '--data', 'fixed=1',
                      ]
        with open('/dev/null', 'w') as fp:
            if subprocess.call(curlcmd, stdout=fp) != 0:
                sys.stderr.write('DOWN {} {} failed'.format(host, service))

# vim: set et sta ts=4 sw=4 :
