#!/usr/bin/env python2
# coding: utf-8

import csv
import sys

statusfilters = [i for i in sys.argv[1].split(',') if i != '']
softstates = sys.argv[2] == '1'

buffered = []
buffered_lens = {}
reader = csv.reader(sys.stdin, delimiter=';', quotechar="'")
for row in reader:
    if statusfilters and not row[2] in statusfilters:
        continue

    attempts = row[5].split('/')
    if row[2] != 'OK' and attempts[0] != attempts[1] and not softstates:
        continue

    buffered.append(row)
    for i in range(len(row)):
        if i in buffered_lens:
            buffered_lens[i] = max(buffered_lens[i], len(row[i]))
        else:
            buffered_lens[i] = len(row[i])

for row in buffered:
    # nbsp:
    print ' ',
    for i in [0, 1, 2, 6]:
        # nbsp at the end of the line:
        fmt = '%-' + str(buffered_lens[i]) + 's '
        print fmt % row[i],
    print
