#!/usr/bin/env python2
# coding: utf-8

import csv
import sys

print """<html>
<head>
    <meta http-equiv="refresh" content="10">
    <style type="text/css">
        html { background-color: #000000 }
        table { border-spacing: 10px }
        td { padding: 5px; text-align: center }
        td.host, td.service { font-size: 42px }
        td.detail { font-size: 24px }
        tr.warning { background-color: #FFFF00 }
        tr.critical { background-color: #FF0000 }
        tr.unknown { background-color: #FF00FF }
        tr.ok { background-color: #BEBEBE }
    </style>
</head>
<body>
    <table>
"""

hostexcludes = [i for i in sys.argv[1].split(',') if i != '']
servicesonly = [i for i in sys.argv[2].split(',') if i != '']
statusfilters = [i for i in sys.argv[3].split(',') if i != '']

reader = csv.reader(sys.stdin, delimiter=';', quotechar="'")
for row in reader:
    host = row[0]
    service = row[1]
    status = row[2]
    detail = row[6]

    if hostexcludes and host in hostexcludes:
        continue

    if servicesonly and service not in servicesonly:
        continue

    if statusfilters and status not in statusfilters:
        continue

    print '<tr class="{}">'.format(status.lower())
    print '<td class="host">{}</td>'.format(host)
    print '<td class="service">{}</td>'.format(service)
    print '<td class="detail">{}</td>'.format(detail)
    print '</tr>'

print '</table></body></html>'

# vim: set et sta ts=4 sw=4 :
